env:
  global:
    - CONAN_UPLOAD="https://lkeb-artifactory.lumc.nl/artifactory/api/conan/conan-local"
    - CONAN_LOGIN_USERNAME="admin"
    - CONAN_PASSWORD=$CONAN_PASSWORD_SECRET

branches:
  #only:
  #  - /testing\/(?!1.8.4)/
  #  - /stable\/(?!1.8.4)/
  # blocklist
  except:
    - /.*/

linux: &linux
  os: linux
  dist: xenial
  language: python
  python: "3.7"
  services:
    - docker
  before_install:
    - chmod +x .ci/pemsetup.sh
    - chmod +x .ci/conan_dependencies.sh
    - chmod +x .ci/set_travis_conan_reference.sh
    - docker pull $DOCKER_IMAGE
    - docker run -itd -v "$(pwd):/home/conan/project" -e TRAVIS_OS_NAME=$TRAVIS_OS_NAME -e CONAN_COMPILERVERSION=$CONAN_COMPILERVERSION -e CONAN_LIBC=$CONAN_LIBC -e CONAN_UPLOAD=$CONAN_UPLOAD -e CONAN_LOGIN_NAME=$CONAN_LOGIN_NAME -e CONAN_PASSWORD=$CONAN_PASSWORD --name build_container $DOCKER_IMAGE
  install:
    - docker exec build_container bash -c "project/.ci/conan_dependencies.sh project"
  script:
    - source .ci/set_travis_conan_reference.sh flann && echo $CONAN_REFERENCE
    - docker exec build_container bash -c "source project/.ci/flann_build_flags.sh; cd project && conan create . $CONAN_REFERENCE --profile action_build"
  after_success:
    - docker exec build_container conan user -p $CONAN_PASSWORD $CONAN_LOGIN_USERNAME -r lkeb-artifactory
    - docker exec build_container conan upload -r lkeb-artifactory --all --force -c $CONAN_REFERENCE

osx: &osx
  os: osx
  language: generic
  before_install:
    - chmod +x .ci/pemsetup.sh
    - chmod +x .ci/conan_dependencies.sh
    - chmod +x .ci/set_travis_conan_reference.sh
  install:
    - .ci/conan_dependencies.sh
  script:
    - source .ci/flann_build_flags.sh
    - source .ci/set_travis_conan_reference.sh flann && echo $CONAN_REFERENCE
    - conan create . $CONAN_REFERENCE --profile action_build
  after_success:
    - conan user -p $CONAN_PASSWORD $CONAN_LOGIN_USERNAME -r lkeb-artifactory
    - conan upload -r lkeb-artifactory --all --force -c $CONAN_REFERENCE

matrix:
  include:
    - <<: *linux
      env:
        - CONAN_COMPILERVERSION=9
          CONAN_COMPILER=gcc
          DOCKER_IMAGE=conanio/gcc9
          CONAN_LIBC=libstdc++

    - <<: *linux
      env:
        - CONAN_COMPILERVERSION=8
          CONAN_COMPILER=gcc
          DOCKER_IMAGE=conanio/gcc8
          CONAN_LIBC=libstdc++

    - <<: *osx
      osx_image: xcode9.4
      env: CONAN_COMPILERVERSION=9.1 CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_ARCHS=x86_64 CONAN_IS_TRAVIS_OSX=1 MACOSX_DEPLOYMENT_TARGET=10.9 HOMEBREW_NO_AUTO_UPDATE=1

    - <<: *osx
      osx_image: xcode10.3
      env: CONAN_COMPILERVERSION=10.0 CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_ARCHS=x86_64 CONAN_IS_TRAVIS_OSX=1 MACOSX_DEPLOYMENT_TARGET=10.13 HOMEBREW_NO_AUTO_UPDATE=1

notifications:
  email:
    recipients:
      - b.van_lew@lumc.nl
    on_success: always # default: change
    on_failure: always # default: always
