env:
    global: 
      -  CONAN_UPLOAD="https://lkeb-artifactory.lumc.nl/artifactory/api/conan/conan-local"
      -  CONAN_LOGIN_USERNAME="admin"
      -  CONAN_PASSWORD=$CONAN_PASSWORD_SECRET  

branches:
  # whitelist
  only:
    - /testing\/(?!1.8.5)/
    - /stable\/(?!1.8.5)/

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
  os: osx
  language: generic
  before_install:
    - chmod +x .ci/pemsetup.sh
    - chmod +x .ci/conan_dependencies.sh
    - chmod +x .ci/set_travis_conan_reference.sh
  install:
    - .ci/conan_dependencies.sh
  script:
    - source .ci/set_travis_conan_reference.sh flann && echo CONAN_REFERENCE
    - conan create . $CONAN_REFERENCE --profile action_build
  after_success:
    - conan user -p $CONAN_PASSWORD $CONAN_LOGIN_USERNAME -r lkeb-artifactory
    - conan upload -r lkeb-artifactory --all --force -c $CONAN_REFERENCE

  
matrix:
   include:
      # - <<: *linux
      #   env:
      #       - CONAN_GCC_VERSIONS=9
      #         CONAN_DOCKER_IMAGE=conanio/gcc9
      #         CONAN_ARCHS=x86_64
      #         CONAN_BUILD_REQUIRES
      #         CONAN_BUILD_TYPES=Release
      #         PYTHON_EXECUTABLE=NOT_FOUND
      #         BUILD_SHARED_LIBS=ON
      #         HDF5_DIR=HDF5-NOT-FOUND
      #         BUILD_PYTHON_BINDINGS=OFF
      #         BUILD_MATLAB_BINDINGS=OFF
      #         BUILD_CUDA_LIB=OFF
      #         BUILD_EXAMPLES=OFF
      #         BUILD_TESTS=OFF
      #         BUILD_DOC=OFF
      #         USE_MPI=OFF
      #         BUILD_C_BINDINGS=ON
      #         HDF5_IS_PARALLEL=OFF
      # - <<: *linux
      #   env:
      #       - CONAN_GCC_VERSIONS=8
      #         CONAN_DOCKER_IMAGE=conanio/gcc8
      #         CONAN_ARCHS=x86_64
      #         CONAN_BUILD_REQUIRES
      #         CONAN_BUILD_TYPES=Release
      #         PYTHON_EXECUTABLE=NOT_FOUND
      #         BUILD_SHARED_LIBS=ON
      #         HDF5_DIR=HDF5-NOT-FOUND
      #         BUILD_PYTHON_BINDINGS=OFF
      #         BUILD_MATLAB_BINDINGS=OFF
      #         BUILD_CUDA_LIB=OFF
      #         BUILD_EXAMPLES=OFF
      #         BUILD_TESTS=OFF
      #         BUILD_DOC=OFF
      #         USE_MPI=OFF
      #         BUILD_C_BINDINGS=ON
      #         HDF5_IS_PARALLEL=OFF
      # - <<: *osx
      #   osx_image: xcode9.4
      #   env:
      #       - CONAN_APPLE_CLANG_VERSIONS=9.1
      #         CONAN_ARCHS=x86_64
      #         CONAN_BUILD_TYPES=Release
      #         PYTHON_EXECUTABLE=NOT_FOUND
      #         BUILD_SHARED_LIBS=ON
      #         HDF5_DIR=HDF5-NOT-FOUND
      #         BUILD_PYTHON_BINDINGS=OFF
      #         BUILD_MATLAB_BINDINGS=OFF
      #         BUILD_CUDA_LIB=OFF
      #         BUILD_EXAMPLES=OFF
      #         BUILD_TESTS=OFF
      #         BUILD_DOC=OFF
      #         USE_MPI=OFF
      #         BUILD_C_BINDINGS=ON
      #         HDF5_IS_PARALLEL=OFF
      - <<: *osx
        osx_image: xcode10.3
        env: CONAN_COMPILERVERSION=10.0 CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_ARCHS=x86_64 CONAN_IS_TRAVIS_OSX=1 MACOSX_DEPLOYMENT_TARGET=10.13 HOMEBREW_NO_AUTO_UPDATE=1

notifications:
  email:
    recipients:
      - b.van_lew@lumc.nl
    on_success: always # default: change
    on_failure: always # default: always
