env:
    global: 
      -  CONAN_STABLE_BRANCH_PATTERN="stable/*"
      -  CONAN_UPLOAD="http://cytosplore.lumc.nl:8081/artifactory/api/conan/conan-local"
      -  CONAN_USERNAME="lkeb" # name used for package reference
      -  CONAN_CHANNEL="stable" # channel used for package naming 
      -  CONAN_LOGIN_USERNAME="admin"
      -  CONAN_PASSWORD=$CONAN_PASSWORD_SECRET  
      -  CONAN_SKIP_CHECK_CREDENTIALS=1
      -  CONAN_UPLOAD_ONLY_WHEN_STABLE=1
      -  CONAN_REMOTES="https://api.bintray.com/conan/bincrafters/public-conan"

branches:
  # whitelist
  only:
    - /testing\/(?!1.8.5)/
    - /stable\/(?!1.8.5)/

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env:
            - CONAN_GCC_VERSIONS=9
              CONAN_DOCKER_IMAGE=conanio/gcc9
              CONAN_ARCHS=x86_64
              CONAN_BUILD_REQUIRES
              CONAN_BUILD_TYPES=Release
              PYTHON_EXECUTABLE=NOT_FOUND
              BUILD_SHARED_LIBS=ON
              HDF5_DIR=HDF5-NOT-FOUND
              BUILD_PYTHON_BINDINGS=OFF
              BUILD_MATLAB_BINDINGS=OFF
              BUILD_CUDA_LIB=OFF
              BUILD_EXAMPLES=OFF
              BUILD_TESTS=OFF
              BUILD_DOC=OFF
              USE_MPI=OFF
              BUILD_C_BINDINGS=ON
              HDF5_IS_PARALLEL=OFF
      - <<: *linux
        env:
            - CONAN_GCC_VERSIONS=8
              CONAN_DOCKER_IMAGE=conanio/gcc8
              CONAN_ARCHS=x86_64
              CONAN_BUILD_REQUIRES
              CONAN_BUILD_TYPES=Release
              PYTHON_EXECUTABLE=NOT_FOUND
              BUILD_SHARED_LIBS=ON
              HDF5_DIR=HDF5-NOT-FOUND
              BUILD_PYTHON_BINDINGS=OFF
              BUILD_MATLAB_BINDINGS=OFF
              BUILD_CUDA_LIB=OFF
              BUILD_EXAMPLES=OFF
              BUILD_TESTS=OFF
              BUILD_DOC=OFF
              USE_MPI=OFF
              BUILD_C_BINDINGS=ON
              HDF5_IS_PARALLEL=OFF
      - <<: *osx
        osx_image: xcode9.4
        env:
            - CONAN_APPLE_CLANG_VERSIONS=9.1
              CONAN_ARCHS=x86_64
              CONAN_BUILD_TYPES=Release
              PYTHON_EXECUTABLE=NOT_FOUND
              BUILD_SHARED_LIBS=ON
              HDF5_DIR=HDF5-NOT-FOUND
              BUILD_PYTHON_BINDINGS=OFF
              BUILD_MATLAB_BINDINGS=OFF
              BUILD_CUDA_LIB=OFF
              BUILD_EXAMPLES=OFF
              BUILD_TESTS=OFF
              BUILD_DOC=OFF
              USE_MPI=OFF
              BUILD_C_BINDINGS=ON
              HDF5_IS_PARALLEL=OFF
      - <<: *osx
        osx_image: xcode10.3
        env:
            - CONAN_APPLE_CLANG_VERSIONS=10.0
              CONAN_ARCHS=x86_64
              CONAN_BUILD_TYPES=Release
              PYTHON_EXECUTABLE=NOT_FOUND
              BUILD_SHARED_LIBS=ON
              HDF5_DIR=HDF5-NOT-FOUND
              BUILD_PYTHON_BINDINGS=OFF
              BUILD_MATLAB_BINDINGS=OFF
              BUILD_CUDA_LIB=OFF
              BUILD_EXAMPLES=OFF
              BUILD_TESTS=OFF
              BUILD_DOC=OFF
              USE_MPI=OFF
              BUILD_C_BINDINGS=ON
              HDF5_IS_PARALLEL=OFF

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh

notifications:
  email:
    recipients:
      - b.van_lew@lumc.nl
    on_success: always # default: change
    on_failure: always # default: always
